[colors]
[colors.primary]
background = "#1A1B26"
foreground = "#e5e6f1"

[colors.normal]
black   = "#1A1B26"
red     = "#977DC8"
green   = "#8E92AE"
yellow  = "#8678B1"
blue    = "#9d9db9"
magenta = "#9C90C6"
cyan    = "#adb0c7"
white   = "#ABAFCF"

[colors.bright]
black   = "#898a9d"
red     = "#cabce5"
green   = "#c3c5d5"
yellow  = "#b9b1d4"
blue    = "#d2d2e0"
magenta = "#d1cbe6"
cyan    = "#e3e4ed"
white   = "#e5e6f1"

[colors.cursor]
text   = "#1A1B26"
cursor = "#e5e6f1"
